### ISSUE TITLE
Responsive Mocks: Participant Registration

### ISSUE THREAD

**Issue by patrickdsantos** [OHCRN/ohcrn-dictionary#9]
Create mobile and tablet mocks for all pages in participant (+clinician) registration flow.

**Comment by b-f-chan** [comment]
@patrickdsantos - Can you please add Captcha to both Participant and Clinician flows?  Confirmed with Michelle and Lauren they want on both.  I did present the pros and cons and they feel we can add it in for both now, and if we find it very burdensome in QA we can disable later.

**Comment by b-f-chan** [comment]
Do not close until Lauren and Kirsten's feedback is also incorporated
